### ISSUE TITLE
SQLServer: Cannot open database "benchbase_tpcc" requested by the login.

### ISSUE THREAD

**Issue by vpetrucci** [cmu-db/benchbase#207]
Hi, 

I am having some issues with SQLServer running TPC-C on my system. I used the sample config found on "config/sqlserver/sample_tpcc_config.xml" and issued:

java -jar benchbase.jar -b tpcc -c config/sqlserver/sample_tpcc_config.xml --create=true --load=true --execute=true

(from the sample config I just changed the login/password entry in there to match my system. The server is active and running. I can log into from SQL Server Management Studio, etc.)

After running the java command, I get the following message below (how to debug this? Is there a way to enable more verbose logging messages?)

[INFO ] 2022-07-11 10:05:50,140 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================
[INFO ] 2022-07-11 10:05:50,303 [main]  com.oltpbenchmark.DBWorkload main - Creating new TPCC database...
[ERROR] 2022-07-11 10:06:04,902 [main]  com.oltpbenchmark.DBWorkload main - Unexpected error when creating benchmark database tables.
com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "benchbase_tpcc" requested by the login. The login failed. ClientConnectionId:fc0233f3-894c-4cf1-9ccb-c992225c07c8
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
        at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:86)
        at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:211)
        at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:626)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:405)

**Comment by bpkroth** [comment]
Hi!  Does the `benchbase_tpcc` database exist and the login has access to it?

**Comment by bpkroth** [comment]
In case you're interested, the steps used for testing this start here:
<https://github.com/cmu-db/benchbase/blob/16e0ad6b3869533cf2b0289b6c2688e043862ddd/.github/workflows/maven.yml#L335>

**Comment by vpetrucci** [comment]
> > com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "benchbase_tpcc" requested by the login. The login failed. ClientConnectionId:fc0233f3-894c-4cf1-9ccb-c992225c07c8
> 
> Hi! Does the `benchbase_tpcc` database exist and the login has access to it?

Hi! the database wasn't created... i thought the command line "--create=true" would do that, no? i will take a look at the steps you posted in the other reply and let you know if i find anything more about it. thanks!!

**Comment by anjagruenheid** [comment]
Create doesn't create the database but only the tables afaik. In essence, it executes the benchmark's ddl that you can see at src/main/resources/benchmarks/tpcc/ddl-$yourdbms.sql.

**Comment by vpetrucci** [comment]
oh, that makes sense now! i really thought created the databases and now it works. sorry for this dumb question. I just followed the README steps: 1) cloned and built BenchBase 2) produced mssql artifact in the target folder 3) run BenchBase... i missed the database creation step. sorry again and thanks for the quick response! i will close this then.
