### ISSUE TITLE
db2 build failure on com.oltpbenchmark.benchmarks.epinions.TestEpinionsLoader

### ISSUE THREAD

**Issue by robert-s-lee** [cmu-db/benchbase#273]
Ran 
```
./mvnw clean package -P db2
```

Error on 

```
[INFO ] 2023-03-27 21:19:23,868 [main]  com.oltpbenchmark.util.ThreadUtil runLoaderThreads - Finished executing 50 Loader Threads [time=0.33s]
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.892 sec <<< FAILURE!
testLoad(com.oltpbenchmark.benchmarks.epinions.TestEpinionsLoader)  Time elapsed: 0.891 sec  <<< FAILURE!
java.lang.AssertionError: No tuples were inserted for table trust
        at com.oltpbenchmark.api.AbstractTestLoader.validateLoad(AbstractTestLoader.java:92)
        at com.oltpbenchmark.api.AbstractTestLoader.testLoad(AbstractTestLoader.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at junit.framework.TestCase.runTest(TestCase.java:177)
        at junit.framework.TestCase.runBare(TestCase.java:142)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:130)
        at junit.framework.TestSuite.runTest(TestSuite.java:241)
        at junit.framework.TestSuite.run(TestSuite.java:236)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running com.oltpbenchmark.benchmarks.epinions.TestEpinionsBenchmark
```

Failure report at the end

```
Results :

Failed tests:   testLoad(com.oltpbenchmark.benchmarks.epinions.TestEpinionsLoader): No tuples were inserted for table trust

Tests run: 215, Failures: 1, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:41 min
[INFO] Finished at: 2023-03-27T21:20:31-04:00
[INFO] ------------------------------------------------------------------------
```

**Comment by bpkroth** [comment]
I've seen this on occasion in the build pipelines as well. Often it works if I retry the failed job, so something seems flaky about that test. Will need some more digging to figure out.
