### ISSUE TITLE
chbenchmark's queries refer to non-existent tables

### ISSUE THREAD

**Issue by alexanderlaw** [cmu-db/benchbase#318]
When running chbenchmark (on 12e3acc56):
java -jar benchbase.jar -b chbenchmark -c config/postgres/chbenchmark_config.xml -create true -load true - -execute true

I get a lot of error messages generated:
chbenchmark: [WARN ] 2023-05-20 03:44:16,025 [CHBenCHmarkWorker<000>]  com.oltpbenchmark.api.Worker doWork - SQLException occurred during [com.oltpbenchmark.benchmarks.chbenchmark.queries.Q8/08] and will not be retried... sql state [42P01], error code [0].
chbenchmark: org.postgresql.util.PSQLException: ERROR: relation "stock" does not exist
chbenchmark:   Position: 162
chbenchmark:    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
chbenchmark:    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
chbenchmark:    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
chbenchmark:    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
chbenchmark:    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
chbenchmark:    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
chbenchmark:    at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
chbenchmark:    at com.oltpbenchmark.benchmarks.chbenchmark.queries.GenericQuery.run(GenericQuery.java:33)
chbenchmark:    at com.oltpbenchmark.benchmarks.chbenchmark.CHBenCHmarkWorker.executeWork(CHBenCHmarkWorker.java:38)
chbenchmark:    at com.oltpbenchmark.api.Worker.doWork(Worker.java:416)
chbenchmark:    at com.oltpbenchmark.api.Worker.run(Worker.java:282)
chbenchmark:    at java.base/java.lang.Thread.run(Thread.java:833)

grep -r 'ERROR: relation "stock" does not exist' run.log | wc -l
937674

Really,
https://github.com/cmu-db/benchbase/blob/main/src/main/resources/benchmarks/chbenchmark/ddl-postgres.sql
and
https://github.com/cmu-db/benchbase/blob/main/src/main/java/com/oltpbenchmark/benchmarks/chbenchmark/CHBenCHmarkLoader.java
don't create and load the table "stock", but it's presented in the benchmark schema:
https://github.com/cmu-db/benchbase/wiki/CH-benCHmark
and used, for example, in https://github.com/cmu-db/benchbase/blob/main/src/main/java/com/oltpbenchmark/benchmarks/chbenchmark/queries/Q2.java

(chbenchmark/queries refer also other non-existent tables)

**Comment by ardentperf** [comment]
for chbenchmark, you need to use syntax `-b chbenchmark,tpcc` - i think this is mentioned in main README, all of the code for handling the tpcc part of the workload is directly shared with that benchmark rather than being duplicated.

**Comment by alexanderlaw** [comment]
Thank you, Jeremy! I have really found that mention in Readme.
Now, when I run
java -jar benchbase.jar -b chbenchmark,tpcc -c config/postgres/chbenchmark_config.xml - -create true - -load true - -execute true
I see the following output:

```
chbenchmark: [INFO ] 2023-08-16 08:16:53,754 [main]  com.oltpbenchmark.DBWorkload runWorkload - Creating 10 virtual terminals...
chbenchmark: [INFO ] 2023-08-16 08:16:53,754 [main]  com.oltpbenchmark.benchmarks.chbenchmark.CHBenCHmark makeWorkersImpl - Creating 10 workers for CHBenCHMark
chbenchmark: [INFO ] 2023-08-16 08:16:53,783 [main]  com.oltpbenchmark.DBWorkload runWorkload - Launching the CHBENCHMARK Benchmark with 1 Phase...
chbenchmark: [INFO ] 2023-08-16 08:16:53,783 [main]  com.oltpbenchmark.DBWorkload runWorkload - Creating 10 virtual terminals...
chbenchmark: [INFO ] 2023-08-16 08:16:53,809 [main]  com.oltpbenchmark.DBWorkload runWorkload - Launching the TPCC Benchmark with 1 Phase...
chbenchmark: [INFO ] 2023-08-16 08:16:53,815 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - PHASE START :: [Workload=CHBENCHMARK] [Serial=false] [Time=120] [WarmupTime=0] [Rate=unlimited] [Arrival=REGULAR] [Ratios=[3.0, 2.0, 3.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]] [ActiveWorkers=10]
chbenchmark: [INFO ] 2023-08-16 08:16:53,815 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - PHASE START :: [Workload=TPCC] [Serial=false] [Time=120] [WarmupTime=0] [Rate=unlimited] [Arrival=REGULAR] [Ratios=[45.0, 43.0, 4.0, 4.0, 4.0]] [ActiveWorkers=10]
chbenchmark: [INFO ] 2023-08-16 08:16:54,814 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - MEASURE :: Warmup complete, starting measurements.
chbenchmark: [INFO ] 2023-08-16 08:18:55,814 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - TERMINATE :: Waiting for all terminals to finish ..
chbenchmark: [INFO ] 2023-08-16 09:12:22,852 [Thread-29]  com.oltpbenchmark.ThreadBench run - Starting WatchDogThread
chbenchmark: [INFO ] 2023-08-16 09:12:22,865 [main]  com.oltpbenchmark.DBWorkload runWorkload - ======================================================================
chbenchmark: [INFO ] 2023-08-16 09:12:22,866 [main]  com.oltpbenchmark.DBWorkload runWorkload - Rate limited reqs/s: Results(nanoSeconds=120999616242, measuredRequests=7676) = 63.43821772664097 requests/sec (throughput), 64.33904702995049 requests/sec (goodput)
```

There are no errors that can be seen before, but it looks like waiting for all terminals to finish took almost one hour. Other time I've seen even longer waiting:
```
chbenchmark: [INFO ] 2023-08-16 04:12:51,209 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - ^[[0;1mMEASURE^[[0;0m :: Warmup complete, starting measurements.
chbenchmark: [INFO ] 2023-08-16 04:14:52,208 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - ^[[0;1mTERMINATE^[[0;0m :: Waiting for all terminals to finish ..
chbenchmark: [INFO ] 2023-08-16 06:55:32,378 [Thread-29]  com.oltpbenchmark.ThreadBench run - Starting WatchDogThread

```
Is this behaviour expected? (I am also somewhat confused by messages "Launching the CHBENCHMARK Benchmark..."/"Launching the TPCC Benchmark...")

**Comment by ardentperf** [comment]
Yes, the behavior is a little confusing.  While the official ch-benchmark is composed of 22 analytical queries alongside a TPCC-like workload, the way it's implemented in benchbase is that the test called "chbenchmark" only runs the analytical queries, and the framework allows you to run two configs at the same time.  So to run a ch-benchmark you run both the config for "chbenchmark" and the config for "tpcc" together.  This helps avoid duplicating all the TPCC code into two places.
