### ISSUE TITLE
Error on Crreating SEATS benchmark table

### ISSUE THREAD

**Issue by amingit21** [cmu-db/benchbase#34]
Hi again,
Similar the previous issue I posted, running "seats" benchmark on  MySQL db fails even at "CREATING" phase. The main thing modified in the default config script is the scale factor. I have set it to 100. 
After making tables with about 5GBs of space, creation phase failed with following errors.
[INFO ] 2021-09-15 01:02:43,297 [main]  com.oltpbenchmark.DBWorkload main - Loading data into SEATS database...
Exception in thread "main" java.lang.RuntimeException: Failed to execute threads: Failed to load data files for scaling-sized table 'flight'
        at com.oltpbenchmark.util.ThreadUtil.run(ThreadUtil.java:106)
        at com.oltpbenchmark.util.ThreadUtil.runNewPool(ThreadUtil.java:70)
        at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:286)
        at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:598)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:418)
Caused by: java.lang.RuntimeException: Failed to load data files for scaling-sized table 'flight'
        at com.oltpbenchmark.benchmarks.seats.SEATSLoader.loadScalingTable(SEATSLoader.java:497)
        at com.oltpbenchmark.benchmarks.seats.SEATSLoader$8.load(SEATSLoader.java:307)
        at com.oltpbenchmark.api.LoaderThread.run(LoaderThread.java:45)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:139)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Failed to load table flight
        at com.oltpbenchmark.benchmarks.seats.SEATSLoader.loadTable(SEATSLoader.java:638)
        at com.oltpbenchmark.benchmarks.seats.SEATSLoader.loadScalingTable(SEATSLoader.java:495)
        ... 6 more
Caused by: java.lang.IllegalArgumentException: FlightId value at position 3 is 65538. Max value is 65535

        at com.oltpbenchmark.util.CompositeId.encode(CompositeId.java:60)
        at com.oltpbenchmark.benchmarks.seats.util.FlightId.encode(FlightId.java:86)
        at com.oltpbenchmark.benchmarks.seats.SEATSLoader$FlightIterable.specialValue(SEATSLoader.java:1358)
        at com.oltpbenchmark.benchmarks.seats.SEATSLoader$ScalingDataIterable$1.next(SEATSLoader.java:841)
        at com.oltpbenchmark.benchmarks.seats.SEATSLoader$ScalingDataIterable$1.next(SEATSLoader.java:827)
        at com.oltpbenchmark.benchmarks.seats.SEATSLoader.loadTable(SEATSLoader.java:550)

Any ideas would be welcomed.
Thanks

**Comment by apavlo** [comment]
We need to switch the `FlightId` to be 128-bits instead of 64-bits:

https://github.com/cmu-db/benchbase/blob/main/src/main/java/com/oltpbenchmark/benchmarks/seats/util/FlightId.java#L32

Try a smaller scalefactor for now.

**Comment by amingit21** [comment]
> We need to switch the `FlightId` to be 128-bits instead of 64-bits:
> 
> https://github.com/cmu-db/benchbase/blob/main/src/main/java/com/oltpbenchmark/benchmarks/seats/util/FlightId.java#L32
> 
> Try a smaller scalefactor for now.

Thanks Apavlo. Actually, smaller scale-factors don't work for us. In the above test, to show the error I was testing with scale-factor 100, but my goal was a much larger scale-factor not smaller one. I intended to test the behavior of a real storage system cache, which is at least 10s of GBs, and naturally, the benchmark should create 100s of GBs worth of Tables to be a meaningful test.

**Comment by amingit21** [comment]
I have tested a few other workloads in BaseBench (or Oltpbench) and they also have more or less similar problems. Only TPCC so far worked for large scale-factors.
