### ISSUE TITLE
Sybase ASE numeric to decimal precision control by running `set arithabort numeric_truncation off` per connection

### ISSUE THREAD

**Issue by robert-s-lee** [cmu-db/benchbase#345]
In the process of adding support for Sybase ASE.   Sybase ASE is throwing below error.

```bash
com.sybase.jdbc4.jdbc.SybSQLException: Scale error during implicit conversion of NUMERIC value '4311.68017578125' to a DECIMAL field.
```

According to [this doc](https://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc00729.1500/html/errMessageAdvRes/BABIDFFD.htm), a way to control this behavior is not to error out as the loss of precision is okay in this context.

This remedy would involve having a way to set the following per connection

```sql
set arithabort numeric_truncation off
```

Is there a way to run this custom on a connection before the workload starts?

Any other options such as possibly limiting the precision of test data to match the schema?

**Comment by apavlo** [comment]
@robert-s-lee Can you provide the full stacktrace so we know what we need to fix? What benchmark?

**Comment by robert-s-lee** [comment]
https://github.com/arcionlabs/benchbase/tree/arcion is the fork that has other adjustments for Sybase ASE

during the loading

```bash
Benchmark:              TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}                                                                                                                                                         
Configuration:          /opt/stage/data/3ef65d74b-23.05.31.7-ase-mysql-snapshot-1/benchbase/src/sample_tpcc_config.xml.83911                                                                                                           
Type:                   SYBASEASE                                                                                                                                                                                                      
Driver:                 com.sybase.jdbc4.jdbc.SybDriver                                                                                                                                                                                
URL:                    jdbc:sybase:Tds:ase-v1602-src-1:5000/arcsrc                                                                                                                                                                    
Isolation:              TRANSACTION_READ_COMMITTED                                                                                                                                                                                     
Batch Size:             1024                                                                                                                                                                                                           
Scale Factor:           1.0                                                                                                                                                                                                            
Terminals:              1                                                                                                                                                                                                              
New Connection Per Txn: false                                                                                                                                                                                                          
                                                                                                                                                                                                                                       
[INFO ] 2023-07-24 20:57:19,048 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================                                                                                     
[INFO ] 2023-07-24 20:57:19,182 [main]  com.oltpbenchmark.DBWorkload main - Creating new TPCC database...                                                                                                                              
[INFO ] 2023-07-24 20:57:19,338 [main]  com.oltpbenchmark.DBWorkload main - Finished creating new TPCC database...                                                                                                                     
[INFO ] 2023-07-24 20:57:19,350 [main]  com.oltpbenchmark.util.SQLUtil getCatalogDirect - Abstract method getSchema() not implemented and will not use schema name.                                                                    
[INFO ] 2023-07-24 20:57:19,400 [main]  com.oltpbenchmark.DBWorkload main - Loading data into TPCC database...                                                                                                                         
[INFO ] 2023-07-24 20:57:19,402 [main]  com.oltpbenchmark.util.ThreadUtil runLoaderThreads - Creating a Thread Pool with a size of 2 to run 2 Loader Threads.  0 threads will be queued.                                               
[INFO ] 2023-07-24 20:57:19,413 [Thread-1]  com.oltpbenchmark.api.LoaderThread run - [CONN46] connection.                                                                                                                              
[INFO ] 2023-07-24 20:59:56,453 [Thread-2]  com.oltpbenchmark.api.LoaderThread run - [CONN46] connection.                                                                                                                              
[ERROR] 2023-07-24 21:02:35,771 [Thread-2]  com.oltpbenchmark.api.Loader loadCustomers - JZ0BE: BatchUpdateException: Error occurred while executing batch statement: Scale error during implicit conversion of NUMERIC value '0.253500
0145435333' to a DECIMAL field.                                                                                                                                                                                                        
                                                                                                                                                                                                                                       
[ERROR] 2023-07-24 21:05:04,459 [Thread-2]  com.oltpbenchmark.api.Loader loadOrderLines - JZ0BE: BatchUpdateException: Error occurred while executing batch statement: Scale error during implicit conversion of NUMERIC value '5046.14
990234375' to a DECIMAL field.                                                                                                                                                                                                         
                                                                                                                                                                                                                                       
java.sql.BatchUpdateException: JZ0BE: BatchUpdateException: Error occurred while executing batch statement: Scale error during implicit conversion of NUMERIC value '5046.14990234375' to a DECIMAL field.                             
                                                                                                                                                                                                                                       
        at com.sybase.jdbc4.jdbc.ErrorMessage.raiseBatchUpdateException(ErrorMessage.java:1398)                                                                                                                                        
        at com.sybase.jdbc4.jdbc.SybStatement.batchLoop(SybStatement.java:2405)                                                                                                                                                        
        at com.sybase.jdbc4.jdbc.SybStatement.sendBatch(SybStatement.java:2185)                                                                                                                                                        
        at com.sybase.jdbc4.jdbc.SybStatement.executeBatch(SybStatement.java:2143)                                                                                                                                                     
        at com.sybase.jdbc4.jdbc.SybStatement.executeBatch(SybStatement.java:2062)                                                                                                                                                     
        at com.sybase.jdbc4.jdbc.SybPreparedStatement.executeBatch(SybPreparedStatement.java:2099)                                                                                                                                     
        at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader.loadOrderLines(TPCCLoader.java:673)                                                                                                                                            
        at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader$2.load(TPCCLoader.java:122)                                                                                                                                                    
        at com.oltpbenchmark.api.LoaderThread.run(LoaderThread.java:47)                                                                                                                                                                
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:145)                                                                                                                                                    
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                                                                                   
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.sybase.jdbc4.jdbc.SybSQLException: Scale error during implicit conversion of NUMERIC value '5046.14990234375' to a DECIMAL field.

        at com.sybase.jdbc4.tds.Tds.processEed(Tds.java:4237)
        at com.sybase.jdbc4.tds.Tds.nextResult(Tds.java:3346)
        at com.sybase.jdbc4.jdbc.ResultGetter.nextResult(ResultGetter.java:78)
        at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:303)
        at com.sybase.jdbc4.jdbc.SybStatement.batchLoop(SybStatement.java:2243)
        ... 11 more
[INFO ] 2023-07-24 21:05:04,463 [main]  com.oltpbenchmark.util.ThreadUtil runLoaderThreads - Finished executing 2 Loader Threads [time=465.06s]
[INFO ] 2023-07-24 21:05:04,464 [main]  com.oltpbenchmark.DBWorkload main - Finished loading data into TPCC database...
[INFO ] 2023-07-24 21:05:04,464 [main]  com.oltpbenchmark.DBWorkload main - Skipping benchmark workload execution
```

during the run
```bash
Benchmark:              TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}                                                                                                                                                [63/1816]
Configuration:          /opt/stage/data/3ef65d74b-23.05.31.7-ase-mysql-snapshot-1/benchbase/src/sample_tpcc_config.xml.84053                                                                                                           
Type:                   SYBASEASE                                                                                                                                                                                                      
Driver:                 com.sybase.jdbc4.jdbc.SybDriver                                                                                                                                                                                
URL:                    jdbc:sybase:Tds:ase-v1602-src-1:5000/arcsrc                                                                                                                                                                    
Isolation:              TRANSACTION_READ_COMMITTED                                                                                                                                                                                     
Batch Size:             128                                                                                                                                                                                                            
Scale Factor:           1.0                                                                                                                                                                                                            
Terminals:              1                                                                                                                                                                                                              
New Connection Per Txn: false                                                                                                                                                                                                          
                                                                                                                                                                                                                                       
[INFO ] 2023-07-24 21:06:07,795 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================                                                                                     
[INFO ] 2023-07-24 21:06:08,037 [main]  com.oltpbenchmark.util.SQLUtil getCatalogDirect - Abstract method getSchema() not implemented and will not use schema name.                                                                    
[INFO ] 2023-07-24 21:06:08,083 [main]  com.oltpbenchmark.DBWorkload runWorkload - Creating 1 virtual terminals...                                                                                                                     
[INFO ] 2023-07-24 21:06:08,094 [main]  com.oltpbenchmark.api.Worker <init> - [CONN 83] connection.                                                                                                                                    
[INFO ] 2023-07-24 21:06:08,096 [main]  com.oltpbenchmark.DBWorkload runWorkload - Launching the TPCC Benchmark with 1 Phase...                                                                                                        
[INFO ] 2023-07-24 21:06:08,098 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - PHASE START :: [Workload=TPCC] [Serial=false] [Time=600] [WarmupTime=0] [Rate=1] [Arrival=REGULAR] [Ratios=[45.0, 43.0, 4.0, 4.0, 4.0]
] [ActiveWorkers=1]                                                                                                                                                                                                                    
[INFO ] 2023-07-24 21:06:08,099 [Thread-2]  com.oltpbenchmark.ThreadBench run - Starting MonitorThread Interval [10000ms]                                                                                                              
[WARN ] 2023-07-24 21:06:08,107 [TPCCWorker<000>]  com.oltpbenchmark.api.Worker doWork - SQLException occurred during [com.oltpbenchmark.benchmarks.tpcc.procedures.Payment/02] and will not be retried... sql state [ZZZZZ], error cod
e [241].                                                                                                                                                                                                                               
com.sybase.jdbc4.jdbc.SybSQLException: Scale error during implicit conversion of NUMERIC value '3427.56005859375' to a DECIMAL field.                                                                                                  
                                                                                                                                                                                                                                       
        at com.sybase.jdbc4.tds.Tds.processEed(Tds.java:4237)                                                                                                                                                                          
        at com.sybase.jdbc4.tds.Tds.nextResult(Tds.java:3346)                                                                                                                                                                          
        at com.sybase.jdbc4.jdbc.ResultGetter.nextResult(ResultGetter.java:78)                                                                                                                                                         
        at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:303)                                                                                                                                                        
        at com.sybase.jdbc4.jdbc.SybStatement.nextResult(SybStatement.java:285)                                                                                                                                                        
        at com.sybase.jdbc4.jdbc.SybStatement.updateLoop(SybStatement.java:2788)                                                                                                                                                       
        at com.sybase.jdbc4.jdbc.SybStatement.executeUpdate(SybStatement.java:2772)                                                                                                                                                    
        at com.sybase.jdbc4.jdbc.SybPreparedStatement.executeUpdate(SybPreparedStatement.java:335)                                                                                                                                     
        at com.oltpbenchmark.benchmarks.tpcc.procedures.Payment.updateWarehouse(Payment.java:280)                                                                                                                                      
        at com.oltpbenchmark.benchmarks.tpcc.procedures.Payment.run(Payment.java:138)                                                                                                                                                  
        at com.oltpbenchmark.benchmarks.tpcc.TPCCWorker.executeWork(TPCCWorker.java:67)                                                                                                                                                
        at com.oltpbenchmark.api.Worker.doWork(Worker.java:420)                                                                                                                                                                        
        at com.oltpbenchmark.api.Worker.run(Worker.java:284)                                                                                                                                                                           
        at java.base/java.lang.Thread.run(Thread.java:833)                                                                                                                                                                             
[INFO ] 2023-07-24 21:06:09,098 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - MEASURE :: Warmup complete, starting measurements.                                                                                    
[WARN ] 2023-07-24 21:06:09,104 [TPCCWorker<000>]  com.oltpbenchmark.api.Worker doWork - SQLException occurred during [com.oltpbenchmark.benchmarks.tpcc.procedures.Payment/02] and will not be retried... sql state [ZZZZZ], error cod
e [241].                                                                                                                                                                                                                               
```

**Comment by apavlo** [comment]
@robert-s-lee I created a draft PR (#346) because I would like to eventually merge in your Informix addition.

We could probably add a new option in the config XML to prefix the connection establishment with a `SET` command. But I feel like you should make a Sybase-specific DDL for TPC-C to avoid this problem. Otherwise somebody else might hit the same issue in the future.

**Comment by robert-s-lee** [comment]
a couple of changes to make Sybase ASE work.  Would be helpful to have the `SET` capability in the future.

added sybase-specific DDL to but preserved precisions to be compatible with other TPCC.
- [tpcc ddl](https://github.com/arcionlabs/benchbase/blob/arcion/src/main/resources/benchmarks/tpcc/ddl-sybasease.sql)
- [dialect](https://github.com/arcionlabs/benchbase/blob/arcion/src/main/resources/benchmarks/tpcc/dialect-sybasease.xml) 
set sybase ase connection properties for the 
- [loader](https://github.com/arcionlabs/benchbase/blob/bdcb7821c012f3ef079e71ea2edd70e85ae14f9d/src/main/java/com/oltpbenchmark/api/LoaderThread.java#L50C1-L58C17)
- [worker](https://github.com/arcionlabs/benchbase/blob/bdcb7821c012f3ef079e71ea2edd70e85ae14f9d/src/main/java/com/oltpbenchmark/api/Worker.java#L82C1-L90C18)

sybase jdbc driver fix
- use [`.newInstance()`](https://github.com/arcionlabs/benchbase/blob/bdcb7821c012f3ef079e71ea2edd70e85ae14f9d/src/main/java/com/oltpbenchmark/WorkloadConfiguration.java#L257C1-L258C1)
- catch [`.getSchema()` error](https://github.com/arcionlabs/benchbase/blob/bdcb7821c012f3ef079e71ea2edd70e85ae14f9d/src/main/java/com/oltpbenchmark/util/SQLUtil.java#L456C1-L462C10)
