### ISSUE TITLE
Find and fix race condition during post-phase checks.

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/benchbase#37]
#36 patches over a race condition where the state disappears and you get a null pointer exception.

I haven't looked into possible causes yet.

**Comment by timveil** [comment]
@lmwnshn I think this has been resolved and I'd favor closing it and reopening should something similar appear again.  I refactored this method as part of PR #83 and likely resolved the issue.

**Comment by lmwnshn** [comment]
@mbutrovich reports hitting this issue with NoOp, PostgreSQL, 200 terminals.

**Comment by mbutrovich** [comment]
```
[INFO ] 2022-07-20 16:01:15,473 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================                              
                                                                                                                                            
Benchmark:     NOOP {com.oltpbenchmark.benchmarks.noop.NoOpBenchmark}
Configuration: /home/protect_the_innocent/noop_postgres.xml           
Type:          POSTGRES                                                                                                                                                                                                                                                                  
Driver:        org.postgresql.Driver                                                                                                        
URL:           jdbc:postgresql:/protect_the_innocent:5432/benchbase?sslmode=disable&ApplicationName=tpcc&reWriteBatchedInserts=true&prepareThreshold=0
Isolation:     TRANSACTION_READ_COMMITTED                 
Batch Size:    128                                                                                                                                                                                                                                                                       
Scale Factor:  1.0                                                                                                                          
Terminals:     200                                                    
                                                                      
[INFO ] 2022-07-20 16:01:15,474 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================                              
[INFO ] 2022-07-20 16:01:15,488 [main]  com.oltpbenchmark.DBWorkload main - Creating new NOOP database...  
[INFO ] 2022-07-20 16:01:15,606 [main]  com.oltpbenchmark.DBWorkload main - Finished creating new NOOP database...
[INFO ] 2022-07-20 16:01:15,637 [main]  com.oltpbenchmark.DBWorkload main - Loading data into NOOP database...
[INFO ] 2022-07-20 16:01:15,638 [main]  com.oltpbenchmark.util.ThreadUtil runLoaderThreads - Creating a Thread Pool with a size of 1 to run 0 Loader Threads.  0 threads will be queued.
[INFO ] 2022-07-20 16:01:15,639 [main]  com.oltpbenchmark.util.ThreadUtil runLoaderThreads - Finished executing 0 Loader Threads [time=0.00s]
[INFO ] 2022-07-20 16:01:15,639 [main]  com.oltpbenchmark.DBWorkload main - Finished loading data into NOOP database...
[INFO ] 2022-07-20 16:01:15,639 [main]  com.oltpbenchmark.DBWorkload runWorkload - Creating 200 virtual terminals...
[INFO ] 2022-07-20 16:01:16,435 [main]  com.oltpbenchmark.DBWorkload runWorkload - Launching the NOOP Benchmark with 1 Phase...                                                                                                                                                          
[INFO ] 2022-07-20 16:01:16,510 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - PHASE START :: [Workload=NOOP] [Serial=false] [Time=60] [WarmupTime=0] [Rate=unlimited] [Arrival=REGULAR] [Ratios=[100.0]] [ActiveWorkers=200]
[INFO ] 2022-07-20 16:01:17,511 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - MEASURE :: Warmup complete, starting measurements.
[INFO ] 2022-07-20 16:02:18,510 [main]  com.oltpbenchmark.ThreadBench runRateLimitedMultiPhase - TERMINATE :: Waiting for all terminals to finish ..
[WARN ] 2022-07-20 16:02:18,511 [NoOpWorker<023>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...                                                                                                                                                                 
[WARN ] 2022-07-20 16:02:18,512 [NoOpWorker<143>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[WARN ] 2022-07-20 16:02:18,512 [NoOpWorker<150>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[WARN ] 2022-07-20 16:02:18,511 [NoOpWorker<190>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[WARN ] 2022-07-20 16:02:18,513 [NoOpWorker<159>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...                                                                                                                                                                 
[WARN ] 2022-07-20 16:02:18,513 [NoOpWorker<127>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[WARN ] 2022-07-20 16:02:18,512 [NoOpWorker<004>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[WARN ] 2022-07-20 16:02:18,512 [NoOpWorker<117>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[WARN ] 2022-07-20 16:02:18,512 [NoOpWorker<083>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...                                                                                                                                                                 
[WARN ] 2022-07-20 16:02:18,512 [NoOpWorker<007>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[WARN ] 2022-07-20 16:02:18,512 [NoOpWorker<183>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[WARN ] 2022-07-20 16:02:18,512 [NoOpWorker<003>]  com.oltpbenchmark.api.Worker run - preState is DONE? will continue...
[ERROR] 2022-07-20 16:02:18,516 [NoOpWorker<182>]  com.oltpbenchmark.ThreadBench uncaughtException - Cannot invoke "com.oltpbenchmark.Phase.getId()" because "postPhase" is null
java.lang.NullPointerException: Cannot invoke "com.oltpbenchmark.Phase.getId()" because "postPhase" is null
        at com.oltpbenchmark.api.Worker.run(Worker.java:296)
        at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 2022-07-20 16:02:18,516 [NoOpWorker<010>]  com.oltpbenchmark.ThreadBench uncaughtException - Cannot invoke "com.oltpbenchmark.Phase.getId()" because "postPhase" is null
java.lang.NullPointerException: Cannot invoke "com.oltpbenchmark.Phase.getId()" because "postPhase" is null
        at com.oltpbenchmark.api.Worker.run(Worker.java:296)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
