### ISSUE TITLE
ERROR: relation "HTABLE" does not exist - HYADAPT for Postgres

### ISSUE THREAD

**Issue by timveil** [cmu-db/benchbase#98]
the file `dialect-postgres.xml` quotes the table name in all the queries... `FROM "HTABLE"`.  This causes the following error which is now properly logged due to #95.  In my original refactor this dialect was removed.  Curious why this was added back.  Updating the dialect file with `FROM htable` resolves the problem.  Thoughts @lmwnshn 

```
[WARN ] 2021-12-27 19:25:42,020 [HYADAPTWorker<000>]  com.oltpbenchmark.api.Worker doWork - SQLException occurred during [com.oltpbenchmark.benchmarks.hyadapt.procedures.ReadRecord5/15] and will not be retried... sql state [42P01], error code [0].
org.postgresql.util.PSQLException: ERROR: relation "HTABLE" does not exist
  Position: 1297
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.oltpbenchmark.benchmarks.hyadapt.procedures.ReadRecord5.run(ReadRecord5.java:43)
	at com.oltpbenchmark.benchmarks.hyadapt.HYADAPTWorker.readRecord5(HYADAPTWorker.java:153)
	at com.oltpbenchmark.benchmarks.hyadapt.HYADAPTWorker.executeWork(HYADAPTWorker.java:66)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:392)
	at com.oltpbenchmark.api.Worker.run(Worker.java:280)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lmwnshn** [comment]
@timveil Go for the update, thanks! I don't remember any reasons for reverting that, could've been a mistake on my part.
